### ISSUE TITLE
Page Headers Newlines Don't work 

### ISSUE THREAD

**Issue by lunarcloud** [humanwhocodes/print-ready#59]
Works in weasyprint but not this.

Example CSS
```css
@page{
  @top-left {
    content: "First\aSecond";
    white-space: pre;
  }
}
```
